FPS_COUNT = 10

DEFAULT_THREADS = 4
DEFAULT_MAX_RESULTS = 1
DEFAULT_SCORE_THRESHOLD = 0.6
DEFAULT_MODEL_FILENAME = "efficientdet_lite0.tflite"

DEFAULT_FPS = 15
DEFAULT_WIDTH = 640
DEFAULT_HEIGHT = 480
DEFAULT_WINDOW_NAME = "detector"

DEFAULT_FRAME_WIDTH_HALF = DEFAULT_WIDTH // 2
DEFAULT_FRAME_HEIGHT_HALF = DEFAULT_HEIGHT // 2

THRESHOLD = 0.7
MAX_RESULTS = 2

TEXT_COLOR = (255, 255, 0)  # cyan
FONT_MARGIN = 10
ROW_SIZE = 10
FONT_SIZE = 1
FONT_THICKNESS = 2
